from __future__ import annotations

from collections.abc import Callable
from copy import deepcopy
from typing import Any

from starlette.types import ASGIApp, Receive, Scope, Send


class DelegatePathsMiddleware:
    """Delegate selected HTTP paths to a separate ASGI app.

    This middleware allows a delegated ASGI app (for example an Axum bridge app)
    to take precedence over FastAPI routes when `should_delegate(path)` returns
    True.
    """

    def __init__(
        self,
        app: ASGIApp,
        delegated_app: ASGIApp,
        should_delegate: Callable[[str], bool] | None = None,
    ) -> None:
        self.app = app
        self.delegated_app = delegated_app
        self.should_delegate = should_delegate or (lambda _path: False)

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope.get("type") != "http":
            await self.app(scope, receive, send)
            return

        path = str(scope.get("path", "/"))
        if self.should_delegate(path):
            await self.delegated_app(scope, receive, send)
            return

        await self.app(scope, receive, send)


def merge_openapi_with_delegate(
    base_schema: dict[str, Any],
    delegated_schema: dict[str, Any] | None,
    mount_prefix: str = "",
) -> dict[str, Any]:
    """Merge delegated OpenAPI paths/components into a host schema.

    Args:
        base_schema: OpenAPI schema generated by the host app.
        delegated_schema: OpenAPI schema from delegated bridge app.
        mount_prefix: Optional prefix if delegated app is mounted under a path.

    Returns:
        Merged OpenAPI schema.
    """
    if not delegated_schema:
        return base_schema

    merged = deepcopy(base_schema)
    merged.setdefault("paths", {})

    prefix = mount_prefix.rstrip("/")
    delegated_paths = delegated_schema.get("paths", {})
    for raw_path, path_item in delegated_paths.items():
        final_path = f"{prefix}{raw_path}" if prefix else raw_path
        merged["paths"][final_path] = path_item

    base_components = merged.setdefault("components", {})
    delegated_components = delegated_schema.get("components", {})
    for section, values in delegated_components.items():
        if isinstance(values, dict):
            base_components.setdefault(section, {})
            base_components[section].update(values)

    return merged


def install_openapi_merger(
    app: Any,
    delegated_app: Any,
    mount_prefix: str = "",
) -> None:
    """Install a custom FastAPI OpenAPI generator that includes delegated routes.

    `delegated_app` should provide `openapi_schema()`.
    """
    original_openapi = app.openapi

    def custom_openapi() -> dict[str, Any]:
        if app.openapi_schema is not None:
            return app.openapi_schema

        base_schema = original_openapi()
        delegated_schema = None
        if hasattr(delegated_app, "openapi_schema"):
            delegated_schema = delegated_app.openapi_schema()

        app.openapi_schema = merge_openapi_with_delegate(
            base_schema=base_schema,
            delegated_schema=delegated_schema,
            mount_prefix=mount_prefix,
        )
        return app.openapi_schema

    app.openapi = custom_openapi


def missing_delegated_routes(
    merged_schema: dict[str, Any],
    delegated_routes: list[str],
    mount_prefix: str = "",
) -> list[str]:
    """Return delegated routes that are missing from merged OpenAPI paths."""
    paths = merged_schema.get("paths", {})
    prefix = mount_prefix.rstrip("/")

    missing: list[str] = []
    for route in delegated_routes:
        expected = f"{prefix}{route}" if prefix else route
        if expected not in paths:
            missing.append(expected)
    return missing
